# Generated by Django 3.2.11 on 2022-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=100, verbose_name='название файла')),
                ('file_upload_time', models.DateTimeField(verbose_name='дата загрузки')),
                ('file_owner', models.CharField(max_length=50, verbose_name='загрузивший')),
            ],
        ),
    ]
